[workspace]

members = [
    "cmd",
    "config",
    "channel",
    "checker",
    "osmosiscli",
    "crypto",
]

[profile.dev]
debug = true

[profile.release]
debug = false

[profile.bench]
debug = false
